name: Build and Run Docker Image on EC2

on:
  push:
    branches:
      - development

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
         
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 50.19.207.153
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.ENV_FILE }}" > /home/ubuntu/.env
            cd /home/ubuntu
            sudo docker build -t archive-matter-admin-front .
            sudo docker run -d --env-file .env -p 80:3000 archive-matter-admin-front
