name: Build and Run Docker Image on EC2

on:
  push:
    branches:
      - development

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: Copy .env file to EC2 instance
        run: scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} .env ubuntu@50.19.207.153:/home/ubuntu/.env

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 50.19.207.153
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Install Docker and other dependencies on the EC2 instance
            sudo apt-get update
            sudo apt-get install -y docker.io

            # Build the Docker image on the EC2 instance
            docker build -t archive-matter-admin-front .

            # Run the Docker container on the EC2 instance
            docker run -d --env-file .env -p 80:3000 archive-matter-admin-front
