name: Build and Run Docker Image on EC2

on:
  push:
    branches:
      - development

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Copy repository to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: 50.19.207.153
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: .
          target: /home/ubuntu/repository
         
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 50.19.207.153
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/repository
            echo "${{ secrets.ENV_FILE }}" > .env
            sudo docker build -t archive-matter-admin-front .
            sudo docker stop archive-matter-admin-front-container || true
            sudo docker rm  archive-matter-admin-front-container || true
            sudo docker run -d --env-file .env --name archive-matter-admin-front-container -p 3000:3000 archive-matter-admin-front
            sudo docker system prune -a -f
