name: Build and Run Docker Image on EC2

on:
  push:
    branches:
      - development

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Copy repository to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: 44.212.226.11
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: .
          target: /home/ubuntu/repository
         
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 44.212.226.111
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/repository
            echo "SERVER_URL=http://50.19.128.91:3000/ \n 
            PORT:3000" > .env
            sudo docker build -t archive-matter-admin-front .
            sudo docker stop archive-matter-admin-front-container || true
            sudo docker rm  archive-matter-admin-front-container || true
            sudo docker run -d --env-file .env --name archive-matter-admin-front-container -p 80:3000 archive-matter-admin-front
            sudo docker system prune -a -f
            
  notify:
    name: Send mail
    runs-on: ubuntu-latest
    needs: [build-and-run]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Pipline of ${{ github.repository }} is Failed
        body: "${{ github.workflow }} has been Failed \nLink to Pipeline https://github.com/${{ github.repository }}/actions"
        to: shivangani@solulab.co
        from: github-action              
